server:
  port: 9090


spring:
  main:
    web-application-type: reactive
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
#        - id: Forecast-Weather-Application
#          uri: http://forecast-weather-svc
        - id: Forecast-Weather-Application
          uri: lb://forecast-weather-application
          predicates:
            - Path=/weather/**


okta:
  oauth2:
    issuer: https://dev-27176195.okta.com/oauth2/default
    audience:  api://default
    client-id:  0oaa8svkacCTWWaGm5d7
    client-secret: lmy5OuSW4BXsb2i_mDnBU5NCxlpaS1G0Hpj_QsjR
    scopes: openid,profile,email,offline_access




